version: "3.7"
services:
  database:
    image: amsterdam/postgres11
    ports:
      - "5415:5432"
    environment:
      POSTGRES_DB: dso_api
      POSTGRES_USER: dso_api
      POSTGRES_PASSWORD: insecure
    volumes:
      - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"
      - .:/host
  importer:
    build:
      context: src/
    links:
      - database
    environment:
      GOB_OBJECTSTORE_PASSWORD:
    volumes:
      - ./src:/app
    command:
        python manage run_import bagh
